Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -35,15 +35,10 @@ jobs:
           LATEST_RELEASE=${{ steps.latest-release.outputs.latest_release }}
           git checkout $LATEST_RELEASE
           git checkout temp/develop
-          if git merge --ff-only $LATEST_RELEASE; then
+          if git merge --no-ff $LATEST_RELEASE; then
             git push origin temp/develop
             echo "Merged $LATEST_RELEASE into develop"
           else
-            echo "$? -eq 128"
-            if [ $? -eq 128 ]; then
-              echo "No new changes to merge. Workflow continues."
-            else
-              echo "Merge conflict detected. Workflow will fail."
-              exit 1  # Exit with a non-zero status code to indicate failure
-            fi
+            echo "Merge conflict detected. Workflow will fail."
+            exit 1  # Exit with a non-zero status code to indicate failure
           fi
